// <auto-generated />
using System;
using APIBiblioteca.Entidades;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIBiblioteca.Migrations
{
    [DbContext(typeof(BibliotecaContext))]
    [Migration("20251217212437_ColumnaDescripcion")]
    partial class ColumnaDescripcion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIBiblioteca.Entidades.Autor", b =>
                {
                    b.Property<int>("AutorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutorId"));

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("AutorId");

                    b.ToTable("Autor");

                    b.HasData(
                        new
                        {
                            AutorId = 1,
                            FechaNacimiento = new DateOnly(1927, 3, 6),
                            Nacionalidad = "Colombiana",
                            Nombre = "Gabriel García Márquez"
                        },
                        new
                        {
                            AutorId = 2,
                            FechaNacimiento = new DateOnly(1947, 9, 21),
                            Nacionalidad = "Estadounidense",
                            Nombre = "Stephen King"
                        },
                        new
                        {
                            AutorId = 3,
                            FechaNacimiento = new DateOnly(1965, 7, 31),
                            Nacionalidad = "Britanica",
                            Nombre = "J.K. Rowling"
                        },
                        new
                        {
                            AutorId = 4,
                            FechaNacimiento = new DateOnly(1892, 1, 3),
                            Nacionalidad = "Britanica",
                            Nombre = "Tolkien"
                        });
                });

            modelBuilder.Entity("APIBiblioteca.Entidades.Libro", b =>
                {
                    b.Property<int>("LibroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LibroId"));

                    b.Property<int>("AutorFK")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Publicacion")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("LibroId");

                    b.HasIndex("AutorFK");

                    b.ToTable("Libro");

                    b.HasData(
                        new
                        {
                            LibroId = 1,
                            AutorFK = 1,
                            Descripcion = "",
                            Publicacion = 1967,
                            Titulo = "Cien Años de Soledad"
                        },
                        new
                        {
                            LibroId = 2,
                            AutorFK = 2,
                            Descripcion = "",
                            Publicacion = 1977,
                            Titulo = "El Resplandor"
                        },
                        new
                        {
                            LibroId = 3,
                            AutorFK = 3,
                            Descripcion = "",
                            Publicacion = 1997,
                            Titulo = "Harry Potter y la Piedra Filosofal"
                        },
                        new
                        {
                            LibroId = 4,
                            AutorFK = 4,
                            Descripcion = "",
                            Publicacion = 1954,
                            Titulo = "El Señor de los Anillos"
                        },
                        new
                        {
                            LibroId = 5,
                            AutorFK = 4,
                            Descripcion = "",
                            Publicacion = 1937,
                            Titulo = "El Hobbit"
                        },
                        new
                        {
                            LibroId = 6,
                            AutorFK = 2,
                            Descripcion = "",
                            Publicacion = 1986,
                            Titulo = "It"
                        },
                        new
                        {
                            LibroId = 7,
                            AutorFK = 1,
                            Descripcion = "",
                            Publicacion = 1981,
                            Titulo = "Crónica de una Muerte Anunciada"
                        },
                        new
                        {
                            LibroId = 8,
                            AutorFK = 3,
                            Descripcion = "",
                            Publicacion = 2007,
                            Titulo = "Harry Potter y las Reliquias de la Muerte"
                        });
                });

            modelBuilder.Entity("APIBiblioteca.Entidades.Libro", b =>
                {
                    b.HasOne("APIBiblioteca.Entidades.Autor", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");
                });
#pragma warning restore 612, 618
        }
    }
}
